[package]
name = "cfrp-detector-cli"
version = "0.1.0"
description = "Command line interface for cfrp-detector"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "cfrp-detector-cli"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
cfrp-detector = { path = "../cfrp-detector" }
csv.workspace = true
figment.workspace = true
futures.workspace = true
indicatif.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true